version: "3"
services:
  db:
    container_name: yu-gi-oh-databse
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: yu_gi_oh
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
